# Generated by Django 5.0.6 on 2024-06-04 06:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(default='09123456789', max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='\\d{10,14}')])),
                ('student_code', models.CharField(max_length=10)),
                ('national_code', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=300)),
                ('fathers_name', models.CharField(max_length=30)),
                ('mothers_name', models.CharField(max_length=30)),
                ('fathers_phone', models.CharField(default='09123456789', max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='\\d{10,14}')])),
                ('mothers_phone', models.CharField(default='09123456789', max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='\\d{10,14}')])),
                ('birth_place', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'ایرانی'), (2, 'اتباع')])),
            ],
        ),
        migrations.CreateModel(
            name='Jozve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField(max_length=500)),
                ('name', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField(max_length=500)),
                ('name', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
